import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Oxanium } from "next/font/google";

export const metadata: Metadata = {
  title: "NLW Connect | DevStage",
  description: "Generated by create next app",
};

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--oxanium-font",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--montserrat-font",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br" className={`antialiased ${oxanium.variable} ${montserrat.variable}`}>
      <body >{children}</body>
    </html>
  );
}
