import type { Metadata } from 'next'
import './globals.css'
import { Montserrat, Oxanium } from 'next/font/google'

export const metadata: Metadata = {
  title: 'NLW Connect | DevStage',
  description: 'Generated by create next app',
}

const oxanium = Oxanium({
  subsets: ['latin'],
  weight: ['500', '600'],
  variable: '--oxanium-font',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700', '500'],
  variable: '--montserrat-font',
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // biome-ignore lint/a11y/useValidLang: <explanation>
    <html lang="pt-br" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="bg-gray-900 text-gray-100  bg-[url(/background.png)] bg-no-repeat md:bg-right-top bg-top">
        <main className="max-w-[1240px] mx-auto px-5 py-8 md:py-0">
          {children}
        </main>
      </body>
    </html>
  )
}
